// Minimal Spigot ABI — just what the x402 middleware and client need
// (mirrors the full ABI in frontend/config.js).
module.exports = [
  { "inputs": [{ "internalType": "uint256", "name": "serviceId", "type": "uint256" }], "name": "callService", "outputs": [{ "internalType": "uint256", "name": "receiptId", "type": "uint256" }], "stateMutability": "nonpayable", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "serviceId", "type": "uint256" }], "name": "payAndCall", "outputs": [{ "internalType": "uint256", "name": "receiptId", "type": "uint256" }], "stateMutability": "payable", "type": "function" },
  { "inputs": [{ "internalType": "address", "name": "", "type": "address" }], "name": "consumerBalance", "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "stateMutability": "view", "type": "function" },
  { "inputs": [], "name": "depositCredit", "outputs": [], "stateMutability": "payable", "type": "function" },
  { "inputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }], "name": "services", "outputs": [{ "internalType": "address", "name": "provider", "type": "address" }, { "internalType": "string", "name": "name", "type": "string" }, { "internalType": "string", "name": "description", "type": "string" }, { "internalType": "uint256", "name": "pricePerCall", "type": "uint256" }, { "internalType": "uint256", "name": "maxCallsPerDay", "type": "uint256" }, { "internalType": "uint256", "name": "registeredAt", "type": "uint256" }, { "internalType": "uint256", "name": "totalCalls", "type": "uint256" }, { "internalType": "uint256", "name": "totalRevenue", "type": "uint256" }, { "internalType": "bool", "name": "active", "type": "bool" }], "stateMutability": "view", "type": "function" },
  { "anonymous": false, "inputs": [{ "indexed": true, "internalType": "uint256", "name": "receiptId", "type": "uint256" }, { "indexed": true, "internalType": "uint256", "name": "serviceId", "type": "uint256" }, { "indexed": true, "internalType": "address", "name": "consumer", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "payout", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "fee", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256" }], "name": "CallSettled", "type": "event" }
];
